name: mesoscopy
channels:
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy==1.21.0
  - pandas==1.3.0
  - conda-forge::pyqtgraph==0.11.0
  - h5py==2.10.0
  - pyqt==5.9.2
  - QtPy
  - jsonschema
  - jupyterlab=3.0.0
  - hypothesis
  - scipy
  - tqdm
  - typing
  - pathlib
  - conda-forge::websockets
  - conda-forge::schema
  - conda-forge::requirements-parser
  - pip:
    - pyvisa==1.11.3
    - qcodes==0.30.1
    - zhinst-qcodes
    - qcodes_contrib_drivers
    - matplotlib==3.4.0
    - PyQt5==5.15.0

