name: mesoscopy
channels:
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy
  - matplotlib
  - qcodes
  - conda-forge::pyqtgraph=0.11.0
  - h5py=2:10.0
  - pyqt=5.9.2
  - QtPy
  - jsonschema
  - jupyter
  - hypothesis
  - scipy
  - pandas
  - tqdm
  - conda-forrge::websockets
conda-forge::schema
conda-forge::requirements-parser
  - pip:
    - pyvisa

