name: mesoscopy
channels:
  - apple
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - pandas==1.3.0
  - conda-forge::pyqtgraph==0.11.0
  - h5py==2.10.0
  - QtPy
  - jsonschema
  - jupyterlab=3.0.0
  - hypothesis
  - scipy
  - tqdm
  - typing
  - pathlib
  - conda-forge::websockets
  - conda-forge::schema
  - conda-forge::requirements-parser
  - conda-forge::matplotlib==3.5.1
  - pyqt>=5.15.0
  - pyvisa-py
  - pip:
    - zhinst-qcodes
    - qcodes_contrib_drivers
    - pyvisa==1.11.3
    - qcodes==0.34.1
