name: build doc
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: install pandoc linux
      run: sudo apt install pandoc
      if: runner.os == 'Linux'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: prepare pip cache
      id: prepare-cache-pip
      uses: ./.github/actions/prepare-cache-pip
    - name: pip cache
      uses: actions/cache@v2.1.6
      with:
        path: ${{ steps.prepare-cache-pip.outputs.cache-dir }}
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/docs_requirements.txt') }}-${{ hashFiles('**/setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.python-version }}-pip-
    #- name: install requirements.txt
    #  run: |
    #    pip install -r requirements.txt
    - name: install docs_requirements.txt
      run: |
        pip install -r ./docs_requirements.txt

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: docs
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.DOC_TOKEN }}
        branch: docs
        force: true
